# Mapas

### Crear archivo para Mapa en masivo

In [14]:
from google.cloud import bigquery
import pandas as pd

# Option 1: Using a service account key file path
client = bigquery.Client.from_service_account_json(r"D:\pe-pacasmayo-analytics-gcp-19997eeb928e.json")

# 2. Define el ID de tu proyecto, dataset y tabla.
# Reemplaza estos valores con los tuyos.
project_id = "pe-pacasmayo-analytics-gcp"
dataset_id = "prod_dwh_comercial_cpsaa"
table_id = "comercial_lcm_zona_comercial"

# 3. Construye la referencia completa a la tabla.
table_ref = f"{project_id}.{dataset_id}.{table_id}"

# 4. Define tu consulta SQL.
# En este caso, seleccionamos todo de la tabla.
sql_query = f"""
    SELECT *
    FROM `{table_ref}`

"""

# 5. Ejecuta la consulta y convierte el resultado a un DataFrame de Pandas.
# El método .to_dataframe() se encarga de todo el trabajo pesado por ti.
try:
    df = client.query(sql_query).to_dataframe()

except Exception as e:
    print(f"Ocurrió un error: {e}")

#df = df[(df['idzonacomercial']!=0)&(df['idzonacomercial']!=10)]

d:\envs\zonas\Lib\site-packages\google\cloud\bigquery\table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

In [15]:
import datetime
df_filter = df[(df["fecha_fin_vigencia"] == datetime.date(2026, 9, 30))&(df["idzonacomercial"] != 0)].copy()
df_filter

,idzonacomercial,deszonacomercial,codigozonacomercial,geometry,codisicom_isicom_asociado,FECRUTINA,FECCARGA,TIPFRECUENCIA,FLGELIMINADO,FECELIMINACION,fecha_inicio_vigencia,fecha_fin_vigencia
0,477.000000000,50008418 - SANTA MARIA 1,264,"{""type"":""Polygon"",""coordinates"":[[[-78.2987697...",201900003665.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30
1,514.000000000,1800009644 - PRISMA,301,"{""type"":""Polygon"",""coordinates"":[[[-80.1717081...",201900011776.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30
2,509.000000000,50102585 - FERRETERIA CORTEZ 1,296,"{""type"":""Polygon"",""coordinates"":[[[-81.033638,...",201900010880.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30
3,526.000000000,50102585 - FERRETERIA CORTEZ 2,313,"{""type"":""Polygon"",""coordinates"":[[[-81.0626087...",201900010880.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30
4,521.000000000,1800005622 - MI KARINA,308,"{""type"":""Polygon"",""coordinates"":[[[-80.6948849...",202000022215.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30
...,...,...,...,...,...,...,...,...,...,...,...,...
186,481.000000000,1800013017 - MEGACONSTRUCCIONES MOSTACERO,268,"{""type"":""Polygon"",""coordinates"":[[[-78.1671497...",202200031545.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30
187,575.000000000,1800013707 - CONSTRUCTORA Y SERVICIOS YATATOS,362,"{""type"":""Polygon"",""coordinates"":[[[-76.3715142...",202200033190.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30
188,479.000000000,50100839 - JUNIOR TORRES,266,"{""type"":""Polygon"",""coordinates"":[[[-78.0506036...",201900001318.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30
189,470.000000000,50013608 - CLEINER COLONIA,257,"{""type"":""Polygon"",""coordinates"":[[[-78.503088,...",201900007827.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30
190,637.000000000,0050100695 - CONSTRUCCIONES Y ALQUILER DE MAQU...,424,"{""type"":""Polygon"",""coordinates"":[[-76.1233997,...",201900018466.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30

In [16]:
from google.cloud import bigquery
import pandas as pd
import datetime
import json
###Validar que las zonas esten cerradas

#json.loads(df_filter["geometry"][154])['coordinates'][0]#[0] ##[-80.1717081, -5.0887526] Validar que las zonas esten cerradas
#json.loads(df_filter["geometry"][154])['coordinates'][0].pop() ##[-80.1717081, -5.0887526]

df_filter["coor1"] = df_filter["geometry"].apply(lambda x: json.loads(x)['coordinates'][0][0])
df_filter["coor2"] = df_filter["geometry"].apply(lambda x: json.loads(x)['coordinates'][0].pop())
df_filter["validacion"] = df_filter["coor1"] == df_filter["coor2"]
df_filter[df_filter["validacion"]==False]

,idzonacomercial,deszonacomercial,codigozonacomercial,geometry,codisicom_isicom_asociado,FECRUTINA,FECCARGA,TIPFRECUENCIA,FLGELIMINADO,FECELIMINACION,fecha_inicio_vigencia,fecha_fin_vigencia,coor1,coor2,validacion
14,627.000000000,0050013274 - CONSTRUCTORA Y FERRETERIA R Y M E...,414,"{""type"":""Polygon"",""coordinates"":[[-76.980596,-...",201900003650.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.980596,-6.027972,False
16,609.000000000,1800000821 - INVERSIONES Y REPRESENTACIONES FV...,396,"{""type"":""Polygon"",""coordinates"":[[-76.7739206,...",201900004015.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.773921,-6.936381,False
19,635.000000000,0050003413 - ARCAMSAG INGENIEROS S.A.C.,422,"{""type"":""Polygon"",""coordinates"":[[-76.133399,-...",201900016796.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.133399,-5.887675,False
30,592.000000000,0050011128 - IMPORTACIONES PATRICIA S.A.C.,379,"{""type"":""Polygon"",""coordinates"":[[-76.7355477,...",201900016023.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.735548,-7.184542,False
36,591.000000000,0050009255 - 3 R SELVA S.A.C.,378,"{""type"":""Polygon"",""coordinates"":[[-76.7354852,...",201900006693.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.735485,-7.184622,False
40,630.000000000,0050010680 - MERCANTIL FERRIMAS E.I.R.L,417,"{""type"":""Polygon"",""coordinates"":[[-77.2957143,...",201900018322.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-77.295714,-5.964716,False
53,625.000000000,0010410274 - COMERCIAL SELVA NOR PERUANA S.A.,412,"{""type"":""Polygon"",""coordinates"":[[-76.9780298,...",201900004014.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.97803,-6.047991,False
57,623.000000000,0050010815 - CONSTRUCTORES Y CONSULTORES BAUPE...,410,"{""type"":""Polygon"",""coordinates"":[[-77.1033904,...",201900018933.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-77.10339,-6.138865,False
58,631.000000000,1800009595 - TRANSMAT ORIENTE SOCIEDAD ANONIMA...,418,"{""type"":""Polygon"",""coordinates"":[[-76.9715024,...",202400037365.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.971502,-6.048258,False
66,622.000000000,0050007996 - PJJR EIRL,409,"{""type"":""Polygon"",""coordinates"":[[-77.1691275,...",201900008977.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-77.169128,-6.052918,False
76,632.000000000,0050014566 - GRUPO DE INVERSIONES CHOMBITA SRL,419,"{""type"":""Polygon"",""coordinates"":[[-76.1222721,...",201900009304.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.122272,-5.881619,False
79,621.000000000,0050008366 - LUBRICANTES SAAVEDRA EIRL,408,"{""type"":""Polygon"",""coordinates"":[[-77.1686983,...",201900001823.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-77.168698,-6.053557,False
81,634.000000000,0050100647 - MAXIMO ALEJANDRO CRUZADO CARRION,421,"{""type"":""Polygon"",""coordinates"":[[-76.1331415,...",201900017382.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.133141,-5.902573,False
99,606.000000000,0050100578 - INVERSION FERRETERA BOLOGNESI E.I...,393,"{""type"":""Polygon"",""coordinates"":[[-76.3343945,...",201900018870.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.334395,-6.907102,False
101,618.000000000,1800019509 - DOMINGO SAUCEDO CABANILLAS 1,405,"{""type"":""Polygon"",""coordinates"":[[-76.4416069,...",202000039184.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.441607,-6.999027,False
102,620.000000000,1800019509 - DOMINGO SAUCEDO CABANILLAS 3,407,"{""type"":""Polygon"",""coordinates"":[[-76.428147,-...",202000039184.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.428147,-6.994077,False
103,619.000000000,1800019509 - DOMINGO SAUCEDO CABANILLAS 2,406,"{""type"":""Polygon"",""coordinates"":[[-76.4619495,...",202000039184.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.46195,-7.020866,False
104,633.000000000,1800010781 - WARE HOUSE PAQUISHA E.I.R.L.,420,"{""type"":""Polygon"",""coordinates"":[[-76.1330438,...",202200030148.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.133044,-5.881064,False
132,598.000000000,0050012977 - EL IMAN FERRETEROS S.A.C. 6,385,"{""type"":""Polygon"",""coordinates"":[[-76.563306,-...",201900004756.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.563306,-7.438431,False
133,593.000000000,0050012977 - EL IMAN FERRETEROS S.A.C. 1,380,"{""type"":""Polygon"",""coordinates"":[[-76.4680006,...",201900004756.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.468001,-7.026957,False
134,602.000000000,0050012977 - EL IMAN FERRETEROS S.A.C. 10,389,"{""type"":""Polygon"",""coordinates"":[[-76.7206443,...",201900004756.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.720644,-7.209106,False
135,594.000000000,0050012977 - EL IMAN FERRETEROS S.A.C. 2,381,"{""type"":""Polygon"",""coordinates"":[[-76.5834258,...",201900004756.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.583426,-7.057968,False
136,601.000000000,0050012977 - EL IMAN FERRETEROS S.A.C. 9,388,"{""type"":""Polygon"",""coordinates"":[[-76.6336127,...",201900004756.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.633613,-7.33794,False
138,595.000000000,0050012977 - EL IMAN FERRETEROS S.A.C. 3,382,"{""type"":""Polygon"",""coordinates"":[[-76.54878,-7...",201900004756.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.54878,-7.052572,False
139,600.000000000,0050012977 - EL IMAN FERRETEROS S.A.C. 8,387,"{""type"":""Polygon"",""coordinates"":[[-76.6574858,...",201900004756.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.657486,-7.300412,False
141,597.000000000,0050012977 - EL IMAN FERRETEROS S.A.C. 5,384,"{""type"":""Polygon"",""coordinates"":[[-76.5588396,...",201900004756.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.55884,-7.478697,False
142,599.000000000,0050012977 - EL IMAN FERRETEROS S.A.C. 7,386,"{""type"":""Polygon"",""coordinates"":[[-76.5709449,...",201900004756.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.570945,-7.408897,False
143,596.000000000,0050012977 - EL IMAN FERRETEROS S.A.C. 4,383,"{""type"":""Polygon"",""coordinates"":[[-76.735026,-...",201900004756.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.735026,-7.184297,False
144,603.000000000,0050012977 - EL IMAN FERRETEROS S.A.C. 11,390,"{""type"":""Polygon"",""coordinates"":[[-76.6873475,...",201900004756.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.687348,-7.171856,False
145,610.000000000,1800012212 - IMAN FERRETERA S.R.L. 1,397,"{""type"":""Polygon"",""coordinates"":[[-76.3317746,...",202200031380.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.331775,-6.918101,False
146,617.000000000,1800012212 - IMAN FERRETERA S.R.L. 8,404,"{""type"":""Polygon"",""coordinates"":[[-76.1359801,...",202200031380.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.13598,-7.018673,False
147,615.000000000,1800012212 - IMAN FERRETERA S.R.L. 6,402,"{""type"":""Polygon"",""coordinates"":[[-76.1985621,...",202200031380.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.198562,-7.003779,False
148,616.000000000,1800012212 - IMAN FERRETERA S.R.L. 7,403,"{""type"":""Polygon"",""coordinates"":[[-76.1692625,...",202200031380.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.169263,-6.995108,False
149,614.000000000,1800012212 - IMAN FERRETERA S.R.L. 5,401,"{""type"":""Polygon"",""coordinates"":[[-76.2378066,...",202200031380.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.237807,-6.990283,False
150,613.000000000,1800012212 - IMAN FERRETERA S.R.L. 4,400,"{""type"":""Polygon"",""coordinates"":[[-76.2521563,...",202200031380.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.252156,-6.934093,False
151,611.000000000,1800012212 - IMAN FERRETERA S.R.L. 2,398,"{""type"":""Polygon"",""coordinates"":[[-76.3109271,...",202200031380.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.310927,-6.891392,False
152,612.000000000,1800012212 - IMAN FERRETERA S.R.L. 3,399,"{""type"":""Polygon"",""coordinates"":[[-76.265126,-...",202200031380.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.265126,-6.895443,False
158,605.000000000,0050100518 - FERROCENTER SAN FELIPE E.I.R.L.,392,"{""type"":""Polygon"",""coordinates"":[[-76.4417678,...",201900001935.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.441768,-6.998963,False
165,608.000000000,0050101992 - INVERSIONES RIOCA & HNOS SOCIEDAD...,395,"{""type"":""Polygon"",""coordinates"":[[-76.7738781,...",201900009686.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.773878,-6.936431,False
166,607.000000000,0050101992 - INVERSIONES RIOCA & HNOS SOCIEDAD...,394,"{""type"":""Polygon"",""coordinates"":[[-76.7710597,...",201900009686.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.77106,-6.977089,False
170,624.000000000,0050100910 - CONSTRUCTORA & CONSULTORA SACMA S...,411,"{""type"":""Polygon"",""coordinates"":[[-77.1033904,...",201900000176.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-77.10339,-6.138865,False
176,626.000000000,0050012586 - COMERCIAL COBA S.A.C.,413,"{""type"":""Polygon"",""coordinates"":[[-76.9651922,...",201900012663.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.965192,-6.034531,False
182,629.000000000,0050006437 - QUIROZ S.R.L.,416,"{""type"":""Polygon"",""coordinates"":[[-77.2955709,...",201900007813.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-77.295571,-5.964904,False
183,604.000000000,0050013706 - COMERCIAL FERRETERIA NUÑEZ SOCIED...,391,"{""type"":""Polygon"",""coordinates"":[[-76.595238,-...",201900009477.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.595238,-7.057619,False
184,636.000000000,1800000524 - GRUPO ARCAMSAG INVERSIONES S.A.C.,423,"{""type"":""Polygon"",""coordinates"":[[-76.1182928,...",201900009202.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.118293,-5.89395,False
185,628.000000000,0050101772 - P&C INVERSIONES GENERALES S.A.C.,415,"{""type"":""Polygon"",""coordinates"":[[-76.980596,-...",201900016441.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.980596,-6.027972,False
190,637.000000000,0050100695 - CONSTRUCCIONES Y ALQUILER DE MAQU...,424,"{""type"":""Polygon"",""coordinates"":[[-76.1233997,...",201900018466.000000000,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,-76.1234,-5.901079,False

In [20]:

# import folium
# import json
# import random

# # 2. Crear el mapa base
# # Centramos el mapa en una ubicación inicial (ej. Lima, Perú). 
# # Ajusta la latitud y longitud si tus datos están en otra parte.
# mapa = folium.Map(location=[-12.08, -77.04], zoom_start=12)

# # 3. Iterar sobre el DataFrame para agregar cada polígono
# for col, fila in df_filter.iterrows():
#     try:
#         print(fila['deszonacomercial'])
#         random_color = f'#{random.randint(0, 0xFFFFFF):06x}'
#         # Extraer el nombre de la zona
#         nombre_zona = fila['deszonacomercial']
        
#         # Cargar la cadena de texto JSON a un diccionario de Python
#         geom_json = json.loads(fila['geometry'])
        
#         # Extraer las coordenadas. La estructura es [lon, lat]
#         # Nota: El JSON puede tener varias listas anidadas, por eso el [0]
#         coordenadas_raw = geom_json['coordinates'][0]
        
#         # Folium necesita las coordenadas en formato [lat, lon]
#         # Creamos una nueva lista invirtiendo el orden de cada par.
#         coordenadas_folium = [[lat, lon] for lon, lat in coordenadas_raw]

#         # 4. Agregar el polígono al mapa
#         folium.Polygon(
#             locations=coordenadas_folium,
#             color=random_color,         # Color del borde
#             fill=True,            # Rellenar el polígono
#             fill_color=random_color,    # Color del relleno
#             fill_opacity=0.7,     # Transparencia del relleno
#             tooltip=nombre_zona,   # Texto que aparece al pasar el mouse
#         ).add_to(mapa)

#     except (json.JSONDecodeError, TypeError, KeyError, IndexError) as e:
#         print(f"No se pudo procesar la fila para '{fila['deszonacomercial']}': {e}")
#         # Esta línea es útil para depurar si algún JSON está mal formado
# mapa
# # 5. Guardar el mapa en un archivo HTML
# mapa.save("mapa_de_zonas.html")

# print("¡Mapa 'mapa_de_zonas.html' generado exitosamente!")
# print("Abre este archivo en tu navegador para ver el resultado.")

import folium
import json
import random

# Crear el mapa base
mapa = folium.Map(location=[-12.08, -77.04], zoom_start=12)

# Iterar sobre el DataFrame para agregar cada polígono
for col, fila in df_filter.iterrows():
    try:
        print(fila['deszonacomercial'])

        random_color = f'#{random.randint(0, 0xFFFFFF):06x}'

        # Extraer el nombre de la zona
        nombre_zona = fila['deszonacomercial']

        # Cargar JSON de geometría
        geom_json = json.loads(fila['geometry'])

        # Extraer coordenadas
        coordenadas_raw = geom_json['coordinates']

        # Validar estructura:
        # Caso normal GeoJSON Polygon:
        # [[[lon, lat], [lon, lat], ...]]
        if isinstance(coordenadas_raw[0][0], list):
            coordenadas_raw = coordenadas_raw[0]

        # Caso aplanado:
        # [[lon, lat], [lon, lat], ...]
        else:
            coordenadas_raw = coordenadas_raw

        # Convertir a formato Folium [lat, lon]
        coordenadas_folium = []

        for punto in coordenadas_raw:
            if isinstance(punto, list) and len(punto) >= 2:
                lon, lat = punto[0], punto[1]
                coordenadas_folium.append([lat, lon])
            else:
                print(f"Punto inválido en {nombre_zona}: {punto}")

        # Validar que tenga puntos suficientes
        if len(coordenadas_folium) < 3:
            print(f"Zona sin suficientes coordenadas: {nombre_zona}")
            continue

        # Agregar polígono al mapa
        folium.Polygon(
            locations=coordenadas_folium,
            color=random_color,
            fill=True,
            fill_color=random_color,
            fill_opacity=0.7,
            tooltip=nombre_zona,
        ).add_to(mapa)

    except Exception as e:
        print(f"No se pudo procesar la fila para '{fila['deszonacomercial']}': {e}")

# Mostrar mapa
mapa

# Guardar HTML
mapa.save("mapa_de_zonas.html")

print("¡Mapa 'mapa_de_zonas.html' generado exitosamente!")
print("Abre este archivo en tu navegador para ver el resultado.")

50008418 - SANTA MARIA 1
1800009644 - PRISMA
50102585 - FERRETERIA CORTEZ 1
50102585 - FERRETERIA CORTEZ 2
1800005622 - MI KARINA
1800002920 - GROSSO 2
1800002920 - GROSSO 1
50003220 - SIDER SELVA 1
50003220 - SIDER SELVA 2
50003220 - SIDER SELVA 4
50003220 - SIDER SELVA 3
50008317 - FERRETERIA SAN MIGUELINO
1800025930 - C Y A
1800001517 - NEGOCIOS ADRIAL
0050013274 - CONSTRUCTORA Y FERRETERIA R Y M E.I.R.L.
1800013053 - GRUPO JEHOVA
1800000821 - INVERSIONES Y REPRESENTACIONES FVC E.I.R.L.
50007406 - SALVADOR
50100377 - FUTURA EVOLUTION
0050003413 - ARCAMSAG INGENIEROS S.A.C.
50100900 - BAISTA 2
50100900 - BAISTA 1
50101092 - MEJIA SANCHEZ RONALDO
1800000473 - JL PC
1800003234 - FERROHOGAR SAN MARTIN 2
1800003234 - FERROHOGAR SAN MARTIN 1
1800003234 - FERROHOGAR SAN MARTIN 3
50014427 - FERRETERIA ESPERANZA
50100545 - DISTRIBUIDORA DE REPUESTOS,LUBRICANTES Y COMBUSTIBLESSRL
50002965 - INVERSIONES BEATRIZ
0050011128 - IMPORTACIONES PATRICIA S.A.C.
44646048 - ACERO COMERCIAL
50002193 - SAN SEBASTIAN
50009508 - DISTRIBUIDORA ALFONSO
50013913 - GRUPO ROJO
50009182 - VASKEVEL
0050009255 - 3 R SELVA S.A.C.
50014188 - FERRETERIA JHONSEMM 2
50014188 - FERRETERIA JHONSEMM 1
50014188 - FERRETERIA JHONSEMM 3
0050010680 - MERCANTIL FERRIMAS E.I.R.L
50001339 - SAN LUIS
50009064 - ESPINOZA MAURICIO DE NORIEGA IRENE
50013838 - NORPERU 1
50013838 - NORPERU 2
50013838 - NORPERU 3
50013838 - NORPERU 4
50009965 - NERUSA
50006283 - COMERCIAL INGRID 2
50006283 - COMERCIAL INGRID 1
50006283 - COMERCIAL INGRID 3
44685728 - REPRESENTACIONES JRZ
10410274 - COMERCIAL SELVA NOR PERUANA 2
0010410274 - COMERCIAL SELVA NOR PERUANA S.A.
10410274 - COMERCIAL SELVA NOR PERUANA 1
1800016491 - JABIAL
50012503 - GRUPO VEA
0050010815 - CONSTRUCTORES Y CONSULTORES BAUPER E. I. R. L.
1800009595 - TRANSMAT ORIENTE SOCIEDAD ANONIMACERRADA
44066599 - COMERCIAL FRANCIS
50102195 - DIMACON
50013359 - FERRETERIA SIAR
1800022010 - FERRETERIA THALIA MANCORA E.I.R.L. 2
1800022010 - FERRETERIA THALIA MANCORA E.I.R.L. 3
1800022010 - FERRETERIA THALIA MANCORA E.I.R.L. 1
50003631 - NEGOCIOS TERAN
0050007996 - PJJR EIRL
1800000211 - SERVICIOS DON ROMULO
1800021469 - R Y V GEMELOS 2
1800021469 - R Y V GEMELOS
1800021469 - R Y V GEMELOS 3
1800021469 - R Y V GEMELOS 4
1800021469 - R Y V GEMELOS 5
50009566 - CUBA
50009566 - CONSTRUCTORA & SG CUBA S.A.C.
50013399 - DIVINO NIÃƒâ€˜O JESUS
0050014566 - GRUPO DE INVERSIONES CHOMBITA SRL
50003544 - Casa Pisfil
50009234 - ABELARDO RIVERA
0050008366 - LUBRICANTES SAAVEDRA EIRL
50009017 - MI FLORITA
0050100647 - MAXIMO ALEJANDRO CRUZADO CARRION
1800009710 - GOMEZ
1800018431 - CONSTRUCTOR 1
50009197 - E&L CASTILLO
50008380 - ESMERALDA CORAL
50008764 - FERPERU
1800008606 - VENTAS Y SERVICIOS HEYSAM
1800001817 - CASA DEL CEMENTO
50014099 - EL OVALO
50006269 - SAN JACINTO 1
50006269 - SAN JACINTO 2
1800017494 - SINCHI 1
50101445 - GRUPO ITANGO
11402283 - ARENERA JAEN
11402283 - ARENERA JAEN
1800000759 - DISTRIBUIDORA DEREK E.I.R.L.
50012528 - FERRETERIA VARGAS CARRION
50011256 - JAVEKA
0050100578 - INVERSION FERRETERA BOLOGNESI E.I.R.L
1800021525 - GRUPO FERROSELVA
1800019509 - DOMINGO SAUCEDO CABANILLAS 1
1800019509 - DOMINGO SAUCEDO CABANILLAS 3
1800019509 - DOMINGO SAUCEDO CABANILLAS 2
1800010781 - WARE HOUSE PAQUISHA E.I.R.L.
50007795 - BERNABE ACEVEDO MARQUINA
50009559 - JM FERRETEROS Y SERVICIOS S.A.C.
23032066 - ALCA
50003356 - EMMANUEL 3
50003356 - EMMANUEL 4
50003356 - EMMANUEL 1
50003356 - EMMANUEL 2
50014551 - FERRETERIA CIELITO
1800011256 - RONAL LUERA
1800019985 - J3L TRANSPORTES
50100963 - COMERCIAL OCHOA HNOS 3
50100963 - COMERCIAL OCHOA HNOS 4
50100963 - COMERCIAL OCHOA HNOS 5
50100963 - COMERCIAL OCHOA HNOS 2
50100963 - COMERCIAL OCHOA HNOS 8
50100963 - COMERCIAL OCHOA HNOS 1
50100963 - COMERCIAL OCHOA HNOS 9
50100963 - COMERCIAL OCHOA HNOS 6
50100963 - COMERCIAL OCHOA HNOS 7
22570064 - COMERCIAL LEO 1
22570064 - COMERCIAL LEO 2
50009981 - PEYMAR
50011923 - GRUPO PAQUISHA
1800019331 - MOVAL GROUP
50101710 - COMERCIAL MARIA SOLEDAD 1
50101710 - COMERCIAL MARIA SOLEDAD 2
1800014418 - YENI GARCIA
0050012977 - EL IMAN FERRETEROS S.A.C. 6
0050012977 - EL IMAN FERRETEROS S.A.C. 1
0050012977 - EL IMAN FERRETEROS S.A.C. 10
0050012977 - EL IMAN FERRETEROS S.A.C. 2
0050012977 - EL IMAN FERRETEROS S.A.C. 9
50012977 - EL IMAN FERRETEROS 2
0050012977 - EL IMAN FERRETEROS S.A.C. 3
0050012977 - EL IMAN FERRETEROS S.A.C. 8
50012977 - EL IMAN FERRETEROS 1
0050012977 - EL IMAN FERRETEROS S.A.C. 5
0050012977 - EL IMAN FERRETEROS S.A.C. 7
0050012977 - EL IMAN FERRETEROS S.A.C. 4
0050012977 - EL IMAN FERRETEROS S.A.C. 11
1800012212 - IMAN FERRETERA S.R.L. 1
1800012212 - IMAN FERRETERA S.R.L. 8
1800012212 - IMAN FERRETERA S.R.L. 6
1800012212 - IMAN FERRETERA S.R.L. 7
1800012212 - IMAN FERRETERA S.R.L. 5
1800012212 - IMAN FERRETERA S.R.L. 4
1800012212 - IMAN FERRETERA S.R.L. 2
1800012212 - IMAN FERRETERA S.R.L. 3
1800021619 - REPRESENTACIONES Y SERVICIOS EL CLAVITOS.R.L.
50100205 - INVERSIONES DIAZ
50102581 - FERRECORD INVERSIONES
50007163 - FERRETERIA SANTA ROSA
1800003655 - SOLUCIONES ACERO
0050100518 - FERROCENTER SAN FELIPE E.I.R.L.
1800015855 - V&M
0050012987 - Virgen de Chinchiquira
1800012494 - SAN MARTIN LAS LOMAS
50011932 - KARINA TORRES
50100081 - ROLY VILLACORTA
1800004838 - ABELARDO CARRERA
0050101992 - INVERSIONES RIOCA & HNOS SOCIEDADANONIMA CERRADA - INVERSIONES RIOCA & HNS.A.C. 2
0050101992 - INVERSIONES RIOCA & HNOS SOCIEDADANONIMA CERRADA - INVERSIONES RIOCA & HNS.A.C. 1
50100865 - FERRETERIA MORENO
1800011660 - FANNI MAYBELLINE FLORES ESCUDERO
1800011467 - ANGIE LEON
0050100910 - CONSTRUCTORA & CONSULTORA SACMA S. R. L.
50003080 - ARNALDO VEGA
1800003573 - CIMIENTOS EL CID
50011703 - DISTRIBUIDORA Y REPRESENTACIONES CULQUI
50011848 - BENITES VASQUEZ PEDRO CELESTINO
50007301 - NERY PRIETO
0050012586 - COMERCIAL COBA S.A.C.
50008152 - VIVAS JACINTO ELIDA MAGNOLIA
1800002882 - LINARES FERRETEROS
1800003436 - MATERIALES CUPISNIQUE
1800005267 - CONSTRUPLAZA
1800018947 - ECHES MATERIALES
0050006437 - QUIROZ S.R.L.
0050013706 - COMERCIAL FERRETERIA NUÑEZ SOCIEDADANONIMA CERRADA
1800000524 - GRUPO ARCAMSAG INVERSIONES S.A.C.
0050101772 - P&C INVERSIONES GENERALES S.A.C.
1800013017 - MEGACONSTRUCCIONES MOSTACERO
1800013707 - CONSTRUCTORA Y SERVICIOS YATATOS
50100839 - JUNIOR TORRES
50013608 - CLEINER COLONIA
0050100695 - CONSTRUCCIONES Y ALQUILER DE MAQUINARIAS S.A.C
¡Mapa 'mapa_de_zonas.html' generado exitosamente!
Abre este archivo en tu navegador para ver el resultado.

### Script para ver 1 geocerca en folium por puntos

### prompt: Quiero que del siguiente formato geo_json, me devuelvas una lista de tuplas, donde se haya invertido el orden de latitud y longuitud de cada punto.

In [6]:
import folium

# Lista de coordenadas para el polígono
polygon_points_5 = [
(-5.0926646, -80.1539263),
(-5.0888174, -80.1537547),
(-5.0889061, -80.1538008),
(-5.0821529, -80.1535752),
(-5.0705985, -80.1432215),
(-5.0558932, -80.1242529),
(-5.0497374, -80.1228796),
(-5.0446076, -80.1275145),
(-5.045377, -80.1325785),
(-5.015623, -80.1303469),
(-5.0133145, -80.1763522),
(-5.0277642, -80.1929175),
(-5.0404181, -80.2121436),
(-5.045548, -80.2066504),
(-5.0475145, -80.19369),
(-5.0390502, -80.1887118),
(-5.0450351, -80.1782404),
(-5.048455, -80.1684557),
(-5.0584669, -80.1621661),
(-5.0608608, -80.1534113),
(-5.0665035, -80.152553),
(-5.081636, -80.1577027),
(-5.0858251, -80.1716075),
(-5.0906983, -80.1714358),
(-5.0940325, -80.1693758),
(-5.0911258, -80.1626811),
(-5.0909547, -80.1582178),
(-5.0912967, -80.1550421),
(-5.0926646, -80.1539263)
]

# --- MEJORA: Centrar el mapa automáticamente en el polígono ---
# Calculamos el punto central de todos los puntos para centrar el mapa.
avg_lat = sum(p[0] for p in polygon_points_5) / len(polygon_points_5)
avg_lon = sum(p[1] for p in polygon_points_5) / len(polygon_points_5)
map_center = [avg_lat, avg_lon]

# Creamos el mapa centrado en el polígono
m = folium.Map(location=map_center, zoom_start=14)

# Agregamos el polígono al mapa (tu código original)
folium.Polygon(
    locations=polygon_points_5,
    color='red',          # Color del borde
    fill=True,
    fill_color='red',     # Color de relleno
    fill_opacity=0.2,     # Opacidad del relleno
    tooltip="1800015855 - V&M"
).add_to(m)

# --- MODIFICACIÓN: Agregar un marcador con número correlativo para cada punto ---
# Usamos enumerate(..., start=1) para obtener un índice (idx) que empieza en 1.
for idx, point in enumerate(polygon_points_5, start=1):
    folium.Marker(
        location=point,
        # En el popup, mostramos el número del punto y sus coordenadas.
        popup=f"<b>Punto {idx}</b><br>Coordenadas:<br>{point[0]}<br>{point[1]}",
        # En el tooltip, mostramos el número del punto para una identificación rápida.
        tooltip=f"Punto {idx}"
    ).add_to(m)
# --- FIN DE LA MODIFICACIÓN ---

# Agregamos un control de capas (opcional, pero útil)
folium.LayerControl().add_to(m)

# -----------------------------------------------------------------
# --- INICIO DE LA MODIFICACIÓN: AGREGAR PUNTO ESPECÍFICO ---
# -----------------------------------------------------------------
# 1. Define las coordenadas de tu punto. ¡Modifica estos valores!
punto_especifico = (-5.09046996, -80.15951995)

# 2. Crea el marcador para ese punto
folium.Marker(
    location=punto_especifico,
    popup="<b>Mi Punto Específico</b><br>¡Ubicación importante!",
    tooltip="Clic para ver detalles",
    # Personaliza el ícono para que se destaque
    icon=folium.Icon(color='blue', icon='star')
).add_to(m)
# -----------------------------------------------------------------
# --- FIN DE LA MODIFICACIÓN ---
# -----------------------------------------------------------------

# Guardamos el mapa en un archivo HTML
output_filename = "mapa_con_poligono_y_puntos_numerados.html"
m.save(output_filename)

print(f"Mapa guardado como '{output_filename}'")

Mapa guardado como 'mapa_con_poligono_y_puntos_numerados.html'

In [4]:
import folium

# Lista de coordenadas para el polígono
polygon_points_5 = [
    (-5.0926646, -80.1539263), (-5.0888174, -80.1537547),
    (-5.0889061, -80.1538008), (-5.0821529, -80.1535752),
    (-5.0705985, -80.1432215), (-5.0558932, -80.1242529),
    (-5.0497374, -80.1228796), (-5.0446076, -80.1275145),
    (-5.045377, -80.1325785), (-5.015623, -80.1303469),
    (-5.0133145, -80.1763522), (-5.0277642, -80.1929175),
    (-5.0404181, -80.2121436), (-5.045548, -80.2066504),
    (-5.0475145, -80.19369), (-5.0390502, -80.1887118),
    (-5.0450351, -80.1782404), (-5.048455, -80.1684557),
    (-5.0584669, -80.1621661), (-5.0608608, -80.1534113),
    (-5.0665035, -80.152553), (-5.081636, -80.1577027),
    (-5.0858251, -80.1716075), (-5.0906983, -80.1714358),
    (-5.0940325, -80.1693758), (-5.0911258, -80.1626811),
    (-5.0909547, -80.1582178), (-5.0912967, -80.1550421),
    (-5.0926646, -80.1539263)
]

# --- Centrar el mapa automáticamente en el polígono ---
avg_lat = sum(p[0] for p in polygon_points_5) / len(polygon_points_5)
avg_lon = sum(p[1] for p in polygon_points_5) / len(polygon_points_5)
map_center = [avg_lat, avg_lon]

# Creamos el mapa centrado
m = folium.Map(location=map_center, zoom_start=14)

# --- Agregamos el polígono al mapa ---
folium.Polygon(
    locations=polygon_points_5,
    color='red',
    fill=True,
    fill_color='red',
    fill_opacity=0.2,
    tooltip="1800015855 - V&M"
).add_to(m)

# --- Agregar un marcador para cada punto del polígono ---
for idx, point in enumerate(polygon_points_5, start=1):
    folium.Marker(
        location=point,
        popup=f"<b>Punto {idx}</b><br>Coordenadas:<br>{point[0]}<br>{point[1]}",
        tooltip=f"Punto {idx}"
    ).add_to(m)

# -----------------------------------------------------------------
# --- INICIO DE LA MODIFICACIÓN: AGREGAR PUNTO ESPECÍFICO ---
# -----------------------------------------------------------------
# 1. Define las coordenadas de tu punto. ¡Modifica estos valores!
punto_especifico = (-5.06, -80.18)

# 2. Crea el marcador para ese punto
folium.Marker(
    location=punto_especifico,
    popup="<b>Mi Punto Específico</b><br>¡Ubicación importante!",
    tooltip="Clic para ver detalles",
    # Personaliza el ícono para que se destaque
    icon=folium.Icon(color='blue', icon='star')
).add_to(m)
# -----------------------------------------------------------------
# --- FIN DE LA MODIFICACIÓN ---
# -----------------------------------------------------------------

# Agregamos un control de capas
folium.LayerControl().add_to(m)

# Guardamos el mapa en un archivo HTML
output_filename = "mapa_con_punto_especifico.html"
m.save(output_filename)

print(f"Mapa guardado como '{output_filename}'")

Mapa guardado como 'mapa_con_punto_especifico.html'

### Colocar georeferencia en forma folium

In [1]:
import json

geo_json_str = '{"type":"Polygon","coordinates":[[[-80.1539263,-5.0926646],[-80.1537547,-5.0888174],[-80.1538008,-5.0889061],[-80.1535752,-5.0821529],[-80.1432215,-5.0705985],[-80.1242529,-5.0558932],[-80.1228796,-5.0497374],[-80.1275145,-5.0446076],[-80.1325785,-5.045377],[-80.1303469,-5.015623],[-80.1763522,-5.0133145],[-80.1929175,-5.0277642],[-80.2121436,-5.0404181],[-80.2066504,-5.045548],[-80.19369,-5.0475145],[-80.1887118,-5.0390502],[-80.1782404,-5.0450351],[-80.1684557,-5.048455],[-80.1621661,-5.0584669],[-80.1534113,-5.0608608],[-80.152553,-5.0665035],[-80.1577027,-5.081636],[-80.1716075,-5.0858251],[-80.1714358,-5.0906983],[-80.1693758,-5.0940325],[-80.1626811,-5.0911258],[-80.1582178,-5.0909547],[-80.1550421,-5.0912967],[-80.1539263,-5.0926646]]]}'

geo_json = json.loads(geo_json_str)

# Extraer la lista de coordenadas
coordinates = geo_json['coordinates'][0]

# Invertir el orden de cada par de coordenadas
inverted_coordinates = [(lat, lon) for lon, lat in coordinates]

# Unir cada tupla con un carácter de nueva línea
output_str = ",\n".join(map(str, inverted_coordinates))

print(output_str)

(-5.0926646, -80.1539263),
(-5.0888174, -80.1537547),
(-5.0889061, -80.1538008),
(-5.0821529, -80.1535752),
(-5.0705985, -80.1432215),
(-5.0558932, -80.1242529),
(-5.0497374, -80.1228796),
(-5.0446076, -80.1275145),
(-5.045377, -80.1325785),
(-5.015623, -80.1303469),
(-5.0133145, -80.1763522),
(-5.0277642, -80.1929175),
(-5.0404181, -80.2121436),
(-5.045548, -80.2066504),
(-5.0475145, -80.19369),
(-5.0390502, -80.1887118),
(-5.0450351, -80.1782404),
(-5.048455, -80.1684557),
(-5.0584669, -80.1621661),
(-5.0608608, -80.1534113),
(-5.0665035, -80.152553),
(-5.081636, -80.1577027),
(-5.0858251, -80.1716075),
(-5.0906983, -80.1714358),
(-5.0940325, -80.1693758),
(-5.0911258, -80.1626811),
(-5.0909547, -80.1582178),
(-5.0912967, -80.1550421),
(-5.0926646, -80.1539263)

### Script para Leer archivos de Apache Beam

In [11]:
import pandas as pd
import ast # Abstract Syntax Tree, necesario para la evaluación segura

# 1. Especifica la ruta a tu archivo .txt
#    Reemplaza esto con la ruta real de tu archivo.
file_path = r'D:\GitLabBQ\proyecto-dataflow-sapbq\enc_vis-00000-of-00001 - copia.txtt'

# 2. Lee el archivo línea por línea y conviértelo a un DataFrame
data_list = []
try:
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            # Elimina espacios en blanco o saltos de línea al inicio/final
            stripped_line = line.strip() 
            if stripped_line: # Procesa la línea solo si no está vacía
                try:
                    # ast.literal_eval convierte de forma segura un string
                    # que parece un objeto de Python (como un dict) a ese objeto.
                    record_dict = ast.literal_eval(stripped_line)
                    data_list.append(record_dict)
                except (ValueError, SyntaxError) as e:
                    print(f"Advertencia: Se omitió una línea por un error de formato: {e}")
                    print(f"Línea con problemas: {stripped_line[:50]}...") # Muestra parte de la línea

    # 3. Crea el DataFrame de pandas a partir de la lista de diccionarios
    df = pd.DataFrame(data_list)

    # 4. Muestra los resultados para verificar
    print("¡Archivo leído exitosamente!")
    print("\nPrimeras 5 filas del DataFrame:")
    print(df.head())

    print("\nInformación del DataFrame:")
    df.info()

except FileNotFoundError:
    print(f"Error: No se pudo encontrar el archivo en la ruta especificada: {file_path}")
except Exception as e:
    print(f"Ocurrió un error inesperado: {e}")

Error: No se pudo encontrar el archivo en la ruta especificada: D:\GitLabBQ\proyecto-dataflow-sapbq\enc_vis-00000-of-00001 - copia.txtt

In [ ]:
import pandas as pd
import ast
import json

data_list = []
file_path = r'D:\GitLabBQ\proyecto-dataflow-sapbq\enc_vis-00000-of-00001 - copia.txt'
with open(file_path, 'r', encoding='utf-8') as f:
    for line in f:
        x = line
        exit

x

In [ ]:
json.dumps(x)

In [ ]:
import apache_beam as beam

with beam.Pipeline(runner='DirectRunner') as p:
    dictionaries = (
      p
      | 'Create PCollection' >> beam.io.ReadFromText(r'D:\GitLabBQ\proyecto-dataflow-sapbq\enc_vis-00000-of-00001 - copia.txt')
      # 2. Aplicamos una transformación. Usamos beam.Map para aplicar la función
      #    ast.literal_eval a cada elemento (en este caso, solo hay uno).
      #| 'Parse String to Dict' >> beam.Map(ast.literal_eval)
      |'printeando'>> beam.Map(lambda x: x["iddia"])
      |'printeando'>> beam.Map(print)
  )

In [ ]:
import seaborn as sns
sns.set_theme(style="whitegrid")

penguins = sns.load_dataset("penguins")

# Draw a nested barplot by species and sex
g = sns.catplot(
    data=penguins, kind="bar",
    x="species X", y="body_mass_g", hue="sex",
    errorbar="sd", palette="dark", alpha=.6, height=6
)
g.despine(left=True)
g.set_axis_labels("", "Body mass (g)")
g.legend.set_title("")

# Scripts para cargar las zonas en archivos geojson en cloudstorage con una metadata geojson para lectura directa.

In [23]:
from google.cloud import bigquery
import pandas as pd

# Option 1: Using a service account key file path
client = bigquery.Client.from_service_account_json(r"D:\pe-pacasmayo-analytics-gcp-19997eeb928e.json")

# 2. Define el ID de tu proyecto, dataset y tabla.
# Reemplaza estos valores con los tuyos.
project_id = "pe-pacasmayo-analytics-gcp"
dataset_id = "prod_dwh_comercial_cpsaa"
table_id = "comercial_lcm_zona_comercial"

# 3. Construye la referencia completa a la tabla.
table_ref = f"{project_id}.{dataset_id}.{table_id}"

# 4. Define tu consulta SQL.
# En este caso, seleccionamos todo de la tabla.
sql_query = f"""
    SELECT *
    FROM `{table_ref}`

"""

# 5. Ejecuta la consulta y convierte el resultado a un DataFrame de Pandas.
# El método .to_dataframe() se encarga de todo el trabajo pesado por ti.
try:
    df = client.query(sql_query).to_dataframe()

except Exception as e:
    print(f"Ocurrió un error: {e}")

#df = df[(df['idzonacomercial']!=0)&(df['idzonacomercial']!=10)]

d:\envs\zonas\Lib\site-packages\google\cloud\bigquery\table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

In [24]:
import json

def to_geojson_feature(row):
    geom = json.loads(row["geometry"])
    feature = {"type": "Feature",
                        "properties": {"idzonacomercial_calc": row["idzonacomercial"]},
        "geometry": geom    }
    return feature

# Lista de todas las combinaciones unicas posibles de codigo isicom + fecha_fin_vigencia
df["codisicom_isicom_asociado"] = df["codisicom_isicom_asociado"].fillna(0)
df["codisicom_isicom_asociado"] = df["codisicom_isicom_asociado"].astype(str)
df["codisicom_isicom_asociado"] = df['codisicom_isicom_asociado'].str.split('.', expand=True)[0]
df["idzonacomercial"] = df["idzonacomercial"].astype(str)
df["idzonacomercial"] = df["idzonacomercial"].str.split('.', expand=True)[0]
df["key"] = df["codisicom_isicom_asociado"] + "_" + df["fecha_fin_vigencia"].astype(str)
df["link"] = "https://raw.githubusercontent.com/arianavk15/SG360/refs/heads/main/" + df["key"] + ".geojson"
df["features"] = df.apply(to_geojson_feature, axis=1).tolist()
df

,idzonacomercial,deszonacomercial,codigozonacomercial,geometry,codisicom_isicom_asociado,FECRUTINA,FECCARGA,TIPFRECUENCIA,FLGELIMINADO,FECELIMINACION,fecha_inicio_vigencia,fecha_fin_vigencia,key,link,features
0,477,50008418 - SANTA MARIA 1,264,"{""type"":""Polygon"",""coordinates"":[[[-78.2987697...",201900003665,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,201900003665_2026-09-30,https://raw.githubusercontent.com/arianavk15/S...,"{'type': 'Feature', 'properties': {'idzonacome..."
1,514,1800009644 - PRISMA,301,"{""type"":""Polygon"",""coordinates"":[[[-80.1717081...",201900011776,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,201900011776_2026-09-30,https://raw.githubusercontent.com/arianavk15/S...,"{'type': 'Feature', 'properties': {'idzonacome..."
2,509,50102585 - FERRETERIA CORTEZ 1,296,"{""type"":""Polygon"",""coordinates"":[[[-81.033638,...",201900010880,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,201900010880_2026-09-30,https://raw.githubusercontent.com/arianavk15/S...,"{'type': 'Feature', 'properties': {'idzonacome..."
3,526,50102585 - FERRETERIA CORTEZ 2,313,"{""type"":""Polygon"",""coordinates"":[[[-81.0626087...",201900010880,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,201900010880_2026-09-30,https://raw.githubusercontent.com/arianavk15/S...,"{'type': 'Feature', 'properties': {'idzonacome..."
4,521,1800005622 - MI KARINA,308,"{""type"":""Polygon"",""coordinates"":[[[-80.6948849...",202000022215,2026-07-01,2026-07-07 16:39:22.841728,D,False,NaT,2026-07-01,2026-09-30,202000022215_2026-09-30,https://raw.githubusercontent.com/arianavk15/S...,"{'type': 'Feature', 'properties': {'idzonacome..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
633,293,1800012494 - SAN MARTIN LAS LOMAS,293,"{""type"":""Polygon"",""coordinates"":[[[-80.235243,...",202200032124,2025-12-31,2025-12-31 16:39:22.841728,D,False,NaT,2026-01-01,2026-03-31,202200032124_2026-03-31,https://raw.githubusercontent.com/arianavk15/S...,"{'type': 'Feature', 'properties': {'idzonacome..."
634,266,50100839 - JUNIOR TORRES,266,"{""type"":""Polygon"",""coordinates"":[[[-78.0506036...",201900001318,2025-12-31,2025-12-31 16:39:22.841728,D,False,NaT,2026-01-01,2026-03-31,201900001318_2026-03-31,https://raw.githubusercontent.com/arianavk15/S...,"{'type': 'Feature', 'properties': {'idzonacome..."
635,276,50100900 - BAISTA 1,276,"{""type"":""Polygon"",""coordinates"":[[[-79.8546116...",201900016521,2025-12-31,2025-12-31 16:39:22.841728,D,False,NaT,2026-01-01,2026-03-31,201900016521_2026-03-31,https://raw.githubusercontent.com/arianavk15/S...,"{'type': 'Feature', 'properties': {'idzonacome..."
636,261,1800019331 - MOVAL GROUP,261,"{""type"":""Polygon"",""coordinates"":[[[-78.5495176...",202400038624,2025-12-31,2025-12-31 16:39:22.841728,D,False,NaT,2026-01-01,2026-03-31,202400038624_2026-03-31,https://raw.githubusercontent.com/arianavk15/S...,"{'type': 'Feature', 'properties': {'idzonacome..."
637,282,1800003655 - SOLUCIONES ACERO,282,"{""type"":""Polygon"",""coordinates"":[[[-79.8397128...",201900020258,2025-12-31,2025-12-31 16:39:22.841728,D,False,NaT,2026-01-01,2026-03-31,201900020258_2026-03-31,https://raw.githubusercontent.com/arianavk15/S...,"{'type': 'Feature', 'properties': {'idzonacome..."

In [25]:
import os

for i in df["key"].unique():
    df_temp = df[df["key"]==i]
    geojson = {
        "type": "FeatureCollection",
        "features": df_temp["features"].to_list()
    }

    ruta_carpeta = "D:/Otros/GitHub_personal/SG360" 
    nombre_archivo = i+".geojson"
    ruta_completa = os.path.join(ruta_carpeta, nombre_archivo)
    os.makedirs(ruta_carpeta, exist_ok=True)

    print(f"Guardando archivo en: {ruta_completa}")
    # Export to .geojson file
    with open(ruta_completa, "w") as f:
        json.dump(geojson, f, indent=0)

print("¡Archivo guardado exitosamente!")

Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900003665_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900011776_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010880_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202000022215_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900019911_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010036_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009173_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202600045653_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900019138_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900003650_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202200032706_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900004015_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010799_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009519_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900016796_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900016521_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900001270_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900015094_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900019792_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900000976_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900004138_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900000023_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900016023_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900008580_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018014_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900007627_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900002616_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009656_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900006693_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900002706_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018322_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900003455_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010713_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900006688_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900002336_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018132_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900002369_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900004014_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202300036251_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900016629_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018933_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202400037365_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900001558_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900008048_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900017629_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202500040906_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900005649_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900008977_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900005758_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202300036459_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900006488_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900008792_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009304_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018847_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018335_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900001823_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018918_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900017382_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202100029158_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202400038118_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900012371_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900001344_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900013722_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202100025754_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900019354_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900002657_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009531_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202400037051_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010408_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900006018_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900016130_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900017007_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900017737_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018870_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202500040848_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202000039184_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202200030148_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018974_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900014072_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900014437_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900017215_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900013740_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202200030636_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202400039449_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900016518_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009056_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900012384_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009184_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202400038624_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900012493_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900020007_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900004756_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202200031380_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202400040468_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900003035_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900003803_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010146_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900020258_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900001935_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202300034447_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900005647_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202200032124_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010985_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900002902_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900004054_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009686_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900006467_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202000021168_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202200031024_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900000176_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900014128_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900020253_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010653_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010487_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900002167_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900012663_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900008932_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202000022225_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900020177_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202000020689_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202400037329_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900007813_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009477_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009202_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900016441_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202200031545_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202200033190_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900001318_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900007827_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018466_2026-09-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900005649_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202400037329_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900020177_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900008932_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010408_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900012493_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900004014_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202100025754_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202500040848_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900016518_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900002706_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010036_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018132_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009056_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010146_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900004756_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900001270_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900017007_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900002369_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900008580_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900003455_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900019792_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900007627_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202400039449_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202200033190_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900017629_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900003803_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202000022225_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010653_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009184_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009173_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900013740_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900006688_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900000976_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202300036459_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010799_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900005758_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009519_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202200031024_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202200031545_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900020258_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900020253_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900017215_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900012371_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900019911_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900002657_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010985_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202400040468_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202000022215_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900016521_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009656_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900020007_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202300034447_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900016629_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900006018_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010880_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900011776_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018014_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900013722_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900002336_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900000023_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900001318_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900008048_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900007827_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900006488_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900014128_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900009531_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900002167_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202300036251_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900002616_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900001344_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900003035_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202400038624_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900008792_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900003665_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202200032706_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018918_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202400037051_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202200032124_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900006467_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202100029158_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900015094_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202200030636_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202000020689_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900019138_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018335_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900005647_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900012384_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018847_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900001558_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900017737_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900014437_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900019354_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202400038118_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900002902_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900004054_2026-06-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900018057_2025-04-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900010036_2025-04-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900011801_2025-04-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900014128_2025-04-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900019911_2025-04-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900017539_2025-04-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\202000022225_2025-04-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900017462_2025-04-30.geojson
Guardando archivo en: D:/Otros/GitHub_personal/SG360\201900017962_2025-04-30.geojson

In [1]:
lista = [1,2,3]

In [ ]:
str(lista)

'[1, 2, 3]'

In [2]:
import sys

In [6]:
sys.argv

['c:\\Users\\fwong\\AppData\\Local\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py',
 '--f=c:\\Users\\fwong\\AppData\\Roaming\\jupyter\\runtime\\kernel-v3c9698856332bb6ad287652aa538683973da2053d.json']

In [50]:
import json
import pandas as pd

df = pd.read_json(r'C:\Users\fwong\Desktop\thunder-file_62a0988e.json')

In [51]:
df

,status,statusCode,timestamp,path,data
0,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': '738d7ba0-c8af-4862-b92c-196640ce7019',..."
1,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': '2fd08ca6-a24d-4bee-814e-a24270305bda',..."
2,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'd19eb664-b189-47df-a6d9-783d4d8f0b03',..."
3,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'd19eb664-b189-47df-a6d9-783d4d8f0b03',..."
4,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'd19eb664-b189-47df-a6d9-783d4d8f0b03',..."
...,...,...,...,...,...
56465,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': '84ed6a65-2844-420d-937a-d08e50fe7eb0',..."
56466,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'f9f10897-dcaf-4d68-aa2d-6e410c239001',..."
56467,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'f9f10897-dcaf-4d68-aa2d-6e410c239001',..."
56468,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'f9f10897-dcaf-4d68-aa2d-6e410c239001',..."
56469,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'f9f10897-dcaf-4d68-aa2d-6e410c239001',..."

In [52]:
df.iloc[1,4]["updatedDate"]

'2025-11-17'

In [53]:
df["updatedDate"] = df["data"].apply(lambda x: x.get("updatedDate", "-"))

In [54]:
df["code"] = df["data"].apply(lambda x: x.get("code", "-"))

In [55]:
df["updatedDate"].max()

'2025-11-17'

In [56]:
df["updatedDate"].min()

'2024-12-26'

In [57]:
df

,status,statusCode,timestamp,path,data,updatedDate,code
0,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': '738d7ba0-c8af-4862-b92c-196640ce7019',...",2025-11-17,145000000136
1,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': '2fd08ca6-a24d-4bee-814e-a24270305bda',...",2025-11-17,53000000574
2,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'd19eb664-b189-47df-a6d9-783d4d8f0b03',...",2025-11-17,105000000408
3,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'd19eb664-b189-47df-a6d9-783d4d8f0b03',...",2025-11-17,105000000408
4,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'd19eb664-b189-47df-a6d9-783d4d8f0b03',...",2025-11-17,105000000408
...,...,...,...,...,...,...,...
56465,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': '84ed6a65-2844-420d-937a-d08e50fe7eb0',...",2025-01-13,10000000002
56466,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'f9f10897-dcaf-4d68-aa2d-6e410c239001',...",2025-01-04,10000000001
56467,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'f9f10897-dcaf-4d68-aa2d-6e410c239001',...",2025-01-04,10000000001
56468,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'f9f10897-dcaf-4d68-aa2d-6e410c239001',...",2025-01-05,10000000001
56469,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'f9f10897-dcaf-4d68-aa2d-6e410c239001',...",2025-01-05,10000000001

In [47]:
len(df["code"].unique())

15919

In [58]:
df

,status,statusCode,timestamp,path,data,updatedDate,code
0,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': '738d7ba0-c8af-4862-b92c-196640ce7019',...",2025-11-17,145000000136
1,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': '2fd08ca6-a24d-4bee-814e-a24270305bda',...",2025-11-17,53000000574
2,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'd19eb664-b189-47df-a6d9-783d4d8f0b03',...",2025-11-17,105000000408
3,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'd19eb664-b189-47df-a6d9-783d4d8f0b03',...",2025-11-17,105000000408
4,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'd19eb664-b189-47df-a6d9-783d4d8f0b03',...",2025-11-17,105000000408
...,...,...,...,...,...,...,...
56465,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': '84ed6a65-2844-420d-937a-d08e50fe7eb0',...",2025-01-13,10000000002
56466,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'f9f10897-dcaf-4d68-aa2d-6e410c239001',...",2025-01-04,10000000001
56467,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'f9f10897-dcaf-4d68-aa2d-6e410c239001',...",2025-01-04,10000000001
56468,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'f9f10897-dcaf-4d68-aa2d-6e410c239001',...",2025-01-05,10000000001
56469,True,200,2025-11-18 01:02:14.594000+00:00,/bizner/report/orders,"{'id': 'f9f10897-dcaf-4d68-aa2d-6e410c239001',...",2025-01-05,10000000001

In [49]:
df[df["code"]=='105000000407']["data"][6]

{'id': 'ae887246-6201-4219-9851-c28d6afca5f2',
 'code': '105000000407',
 'status': 'PENDING_CONFIRMATION',
 'vendor': {'id': '7e50a4ca-b71a-4b18-9b51-ca67061cec92',
  'ruc': '20487625061',
  'code': '201900000047',
  'name': 'PALMANDINA S.A.C.',
  'ubigeo': '140105',
  'erpCode': None},
 'channel': None,
 'creator': None,
 'erpCode': None,
 'payment': {'name': 'EFECTIVO',
  'type': None,
  'erpCode': None,
  'provider': None,
  'transactionId': None,
  'paymentMethodCode': 'CASH'},
 'pricing': {'tax': None,
  'total': 283.9,
  'subtotal': 283.9,
  'deliveryCost': None,
  'adjustmentsTotal': None},
 'comments': None,
 'customer': {'id': '4457374d-8c66-4093-b41e-ac0d6980a1e2',
  'ruc': '10408626175',
  'code': '201900008448',
  'phone': '979650458',
  'lastName': 'Ramirez',
  'firstName': 'Walter',
  'loginCode': None,
  'businessName': 'Ferretería QUINTOS',
  'corporateEmail': 'walterpilarramirezquintos@gmail.com',
  'addressUbigeoCode': '140105'},
 'shipping': {'name': None,
  'deliveryDate': '2025-11-17T00:00:00.000Z',
  'deliveryAddress': {'id': 'f45be5df-1f3b-4f15-9dc2-d4dc840ba0cf',
   'code': None,
   'address': 'AV AGRICULTURA S/N CARRETERA A PICSI',
   'comment': None,
   'erpCode': None,
   'apartment': None,
   'contactEmail': 'walterpilarramirezquintos@gmail.com',
   'localityTree': [{'code': '14',
     'name': 'LAMBAYEQUE',
     'division': 'DEPARTAMENTO'},
    {'code': '1401', 'name': 'CHICLAYO', 'division': 'PROVINCIA'},
    {'code': '140105', 'name': 'JOSE LEONARDO ORTIZ', 'division': 'DISTRITO'}],
   'divisionLevel1': 'LAMBAYEQUE',
   'divisionLevel2': 'CHICLAYO',
   'divisionLevel3': 'JOSE LEONARDO ORTIZ',
   'divisionLevel4': None,
   'contactDocumentNumber': '40862617'},
  'deliveryEndTime': '13:00:00',
  'deliveryStartTime': '09:00:00',
  'deliveryTimeRange': '04:00'},
 'createdAt': '2025-11-17 08:29:05',
 'inventory': None,
 'invoicing': None,
 'lineItems': [{'id': '38ad347d-802d-4893-8dd9-f65de8c87aed',
   'erpCode': None,
   'quantity': 10,
   'priceUnit': 28.39,
   'productId': '35872c81-8bd8-4434-8e9d-4ab9af0f3060',
   'productSku': 'ab98327b-1ba9-4e51-91d0-da229261012a',
   'extraFields': None,
   'productName': 'Mochica Gu',
   'skuBusiness': '004-02653',
   'presentation': 'Bolsa de 42.5 kilos',
   'adjustmentsTotal': None}],
 'orderType': 'STORE_ORDER',
 'updatedAt': '2025-11-17 08:29:06',
 'userAgent': None,
 'giftMessage': None,
 'updatedDate': '2025-11-17',
 'updatedTime': '08:29:06',
 'creationDate': '2025-11-17',
 'creationTime': '08:29:05',
 'allAdjustments': None,
 'dedicationMessage': None}